ofcourse/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import patterns, include, url
from login.views import RegistrationView,login,HomePageView
from django.contrib.auth import views
from courses.views import CourseContent,CourseListView,CategoryListView,enrollCourse,IcerikleriGoruntule,IcerikGoruntule,kurstanayril
from instructor.views import InstructorPanel,CreateCourseView,UpdateCourseView,IcerikEkleView
from courses.models import Course
from ouser.views import KullaniciBilgileri, kullanici_duzenle

from forum.views import BaslikAc,QA,SoruDetay
from main.views import gizlilik_politikasi, destek, hakkimizda, iletisim

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomePageView.as_view()),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

urlpatterns += patterns('',
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root':settings.MEDIA_URL}),
    (r'^search/', include('haystack.urls')),
)

urlpatterns += [
    url(r'^register/$', RegistrationView.as_view(), name='register'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$','django.contrib.auth.views.logout',name='logout',kwargs={'next_page': '/'}),

    url(r'^kurs/(?P<course_ID>\d+)/$',CourseContent.as_view(), name='slug'),
    url(r'^kurs/(?P<course_ID>\d+)/icerik/$',IcerikleriGoruntule.as_view(), name='icerik'),
    url(r'^kurs/(?P<course_ID>\d+)/icerik/sil/$', kurstanayril),
    url(r'^kurs/(?P<course_ID>\d+)/icerik/(?P<slug>[\w-]+)/$', IcerikGoruntule.as_view()),
    url(r'^kurs/(?P<course_ID>\d+)/enroll/$',enrollCourse, name='enroll'),
    url(r'^kurs/(?P<course_ID>\d+)/forum/baslikac/$',BaslikAc.as_view() ),
    url(r'^kurs/(?P<course_ID>\d+)/forum/$', QA.as_view()),
    url(r'^kurs/(?P<course_ID>\d+)/forum/(?P<question_ID>\d+)/$', SoruDetay.as_view(),name="cevapyolla"),


    url(r'^kursduzenle/(?P<pk>\d+)/$',UpdateCourseView.as_view(), name='kursduzenle'),
    url(r'^kursduzenle/(?P<pk>\d+)/icerikekle/$',IcerikEkleView.as_view()),


    url(r'^kurslar/$', CourseListView.as_view() ,name='kurslar'),
    url(r'^kullanici/(?P<username>.*)/$', KullaniciBilgileri.as_view() ,name='username'),
    url(r'^profil-duzenle/$', kullanici_duzenle),

    url(r'^egitmen/$', InstructorPanel.as_view() ,name='egitmen'),
    url(r'^kursolustur/$', CreateCourseView.as_view() ,name='kursolustur'),


    # statik sayfalar

    url(r'gizlilik-politikasi/$', gizlilik_politikasi),
    url(r'destek/$', destek),
    url(r'hakkimizda/$', hakkimizda),
    url(r'iletisim/$', iletisim),

]

forum/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from ouser.models import OUser
from django.conf import settings

class Question(models.Model):
    id = models.AutoField(primary_key=True)
    question_text = models.CharField(max_length=200)
    question_title = models.CharField(max_length=200,null=True)
    pub_date = models.DateTimeField('date published',default=timezone.now)
    closed = models.BooleanField(default=False)
    user = models.ForeignKey(OUser,null=True)
    course = models.ForeignKey('courses.course',null=True)

    def __str__(self):
        return self.question_title


class Answer(models.Model):
    question = models.ForeignKey(Question,null=True)
    answer_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    pub_date = models.DateTimeField('date published',null=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,null=True)

    def __str__(self):
        return self.answer_text

class Voter(models.Model):
    user = models.ForeignKey(OUser)
    answer = models.ForeignKey(Answer)

class QVoter(models.Model):
    user = models.ForeignKey(OUser)
    question = models.ForeignKey(Question)

class Comment(models.Model):
    answer = models.ForeignKey(Answer)
    comment_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    user_data = models.ForeignKey(OUser)

    def __str__(self):
        return self.comment_text

templates/qa/list.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Questions</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="description" content="" />
<link href="/site_media/css/bootstrap.min.css" rel="stylesheet" />
<link href="/site_media/css/style.css" rel="stylesheet" />
<link href="/site_media/skins/default.css" rel="stylesheet" />
<link href="/site_media/skins/main.css" rel="stylesheet" />

</head>
<body>

<div id="wrapper">
    {% include "base/nav.html" %}
    <hr>
    <div class="container">
    <a href="baslikac"><button type="button" class="btn btn-primary" >Yeni Başlık Aç</button></a>

    <div class="row">
        <div id="content">
        {% for x in lastquestions %}
		<div class="widget widget-gray">
				<div class="widget-head" >
					<a href="{{ x.id }}" target="_blank">
                        <h4 class="heading" ><i class="fa fa-briefcase"></i>{{ x.question_title }}</h4>
                    </a>
                </div>
            <div class="widget-body">{{ x.question_text }}</div>
        </div> <br>
        {% endfor %}
        </div>
	</div>
</div>






</body>
</html>

templates/qa/ques_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <link href="/site_media/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/site_media/css/style.css" rel="stylesheet" />
    <link href="/site_media/skins/default.css" rel="stylesheet" />
    <title>Question - {{ question_details.question_title }}</title>
</head>

<body>
<div id="wrapper">
    {% include "base/nav.html" %}
    <div class="container">
        <hr>
        <div class="media">
            {% if question_details.user.profile_pic %}
            <a href="#" class="pull-left"><img  width=128 height=128 src="http://127.0.0.1:8000/media/{{ question_details.user.profile_pic }}" class="media-photo"></a>
            {% endif %}
            <div class="media-body">
			<span class="media-meta pull-right">{{ question_details.pub_date }}</span>
                <strong>{{ question_details.user.first_name }} {{ question_details.user.last_name }} tarafından soruldu,</strong>
                <strong><h4 class="title">{{ question_details.question_title }}</h4></strong>
				<p class="summary">{{ question_details.question_text }}</p>
            </div>
        </div>
        <hr>

        <div class="col-sm-12">
            <h3>Cevaplar</h3>
        </div>
        {% if lastanswers %}
        {% for ans in lastanswers %}
        <div class="row">
            <div class="col-sm-1">
                <div class="thumbnail">
                    <img class="img-responsive user-photo" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
                </div>
            </div>
            <div class="col-sm-11">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <strong>{{ ans.author }}</strong> <span class="text-muted">yorumladı , {{ ans.pub_date|date:"d M Y" }} {{ ans.pub_date |time:"H:i" }} tarihinde</span>
                    </div>
                    <div class="panel-body">
                        {{ ans.answer_text }}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
            Bu soru cevaplanmamıştır.
        {% endif %}


        <div class="row">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Yanıtınız
                </div>
                <div class="panel-body">
                    <form method="POST" class="form-horizontal"  >
                    {% csrf_token %}
                    <textarea rows="6" cols="138" id="id_answer_text" maxlength="200" name="answer_text" type="text" > </textarea>
                    <button type="submit" class="save btn btn-success">Gönder</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

</body>

</html>