ofcourse/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import patterns, include, url
from login.views import RegistrationView,login,HomePageView
from django.contrib.auth import views
from courses.views import CourseContent,CourseListView,CategoryListView,enrollCourse,IcerikleriGoruntule,IcerikGoruntule,kurstanayril
from instructor.views import InstructorPanel,CreateCourseView,UpdateCourseView,IcerikEkleView
from courses.models import Course
from ouser.views import KullaniciBilgileri, kullanici_duzenle

from forum.views import BaslikAc,QA,SoruDetay
from main.views import gizlilik_politikasi, destek, hakkimizda, iletisim

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomePageView.as_view()),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

urlpatterns += patterns('',
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root':settings.MEDIA_URL}),
    (r'^search/', include('haystack.urls')),
)

urlpatterns += [
    url(r'^register/$', RegistrationView.as_view(), name='register'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$','django.contrib.auth.views.logout',name='logout',kwargs={'next_page': '/'}),

    url(r'^kurs/(?P<course_ID>\d+)/$',CourseContent.as_view(), name='slug'),
    url(r'^kurs/(?P<course_ID>\d+)/icerik/$',IcerikleriGoruntule.as_view(), name='icerik'),
    url(r'^kurs/(?P<course_ID>\d+)/icerik/sil/$', kurstanayril),
    url(r'^kurs/(?P<course_ID>\d+)/icerik/(?P<slug>[\w-]+)/$', IcerikGoruntule.as_view()),
    url(r'^kurs/(?P<course_ID>\d+)/enroll/$',enrollCourse, name='enroll'),
    url(r'^kurs/(?P<course_ID>\d+)/forum/baslikac/$',BaslikAc.as_view() ),
    url(r'^kurs/(?P<course_ID>\d+)/forum/$', QA.as_view()),
    url(r'^kurs/(?P<course_ID>\d+)/forum/(?P<question_ID>\d+)/$', SoruDetay.as_view(),name="cevapyolla"),


    url(r'^kursduzenle/(?P<pk>\d+)/$',UpdateCourseView.as_view(), name='kursduzenle'),
    url(r'^kursduzenle/(?P<pk>\d+)/icerikekle/$',IcerikEkleView.as_view()),


    url(r'^kurslar/$', CourseListView.as_view() ,name='kurslar'),
    url(r'^kullanici/(?P<username>.*)/$', KullaniciBilgileri.as_view() ,name='username'),
    url(r'^profil-duzenle/$', kullanici_duzenle),

    url(r'^egitmen/$', InstructorPanel.as_view() ,name='egitmen'),
    url(r'^kursolustur/$', CreateCourseView.as_view() ,name='kursolustur'),


    # statik sayfalar

    url(r'gizlilik-politikasi/$', gizlilik_politikasi),
    url(r'destek/$', destek),
    url(r'hakkimizda/$', hakkimizda),
    url(r'iletisim/$', iletisim),

]

courses/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils.text import slugify
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Category(models.Model):
    cid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=150)
    slug = models.SlugField()
    parent = models.ForeignKey('self', blank=True, null=True, related_name="children")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


@python_2_unicode_compatible
class Course(models.Model):
    LEVEL_CHOICES = (
        ('Beginner','Beginner'),
        ('Intermediate','Intermediate'),
        ('Advanced','Advanced'),
    )
    courseID = models.AutoField(primary_key=True)
    course_isActive = models.BooleanField(default=False)
    courseName = models.CharField(max_length=200,verbose_name="Kurs Adi")
    courseSlug = models.SlugField()
    courseDesc = models.TextField()
    courseCoverPhoto = models.ImageField(upload_to='covers/',default='covers/default.jpg')
    coursePreVideo = models.URLField()
    courseStartDate = models.DateField(null=True,blank=True)
    courseUpdateDate = models.DateField(null=True,blank=True)
    courseLanguage = models.ForeignKey('courses.CourseLanguage',blank=True,null=True,verbose_name="Dil")
    courseLevel = models.ForeignKey('courses.CourseLevels',blank=True,null=True,verbose_name="Seviye")
    courseCategory = models.ForeignKey('courses.Category',blank=True,null=True,verbose_name="Kategori")
    courseInstructor = models.ForeignKey('instructor.Instructor',blank=True,null=True,default="")

    def save(self, *args, **kwargs):
        self.courseSlug = slugify(self.courseName)
        self.courseStartDate = timezone.now()
        self.courseUpdateDate = None
        super(Course, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Kurs'
        verbose_name_plural = 'Kurslar'

    def __str__(self):
        return self.courseName


@python_2_unicode_compatible
class CourseLanguage(models.Model):
    courseLanguage = models.CharField(max_length=200)

    class Meta:
        verbose_name = 'Kurs Dili'
        verbose_name_plural = 'Kurs Dilleri'

    def __str__(self):
        return self.courseLanguage


@python_2_unicode_compatible
class CourseLevels(models.Model):
    courseLevel = models.CharField(max_length=200)

    class Meta:
        verbose_name = 'Kurs Seviyeleri'
        verbose_name_plural = 'Kurs Seviyeleri'

    def __str__(self):
        return self.courseLevel

courses/forms.py
from django import forms
from .models import Course
from django.utils import timezone
from django.http import HttpResponse


class CreateCourseForm(forms.ModelForm):    # kurs olusturma formu
    courseName = forms.CharField()

    class Meta:
        model = Course
        fields = ['courseName']

    def form_valid(self, form):             # form gecerli ise
        cf = form.save(commit=False)
        cf.courseInstructor = self.request.user
        cf.courseStartDate = timezone.now()
        cf.save()
        return HttpResponse("Kursunuz olusturulmustur")

courses/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Course,CourseLevels,CourseLanguage
from instructor.models import Lecture,Section
from ouser.models import OUser
from django.views.generic import ListView,DetailView
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import get_object_or_404,redirect
from django.http import Http404
from .filters import CourseFilter

# http://127.0.0.1/kurs/kurs-id
class CourseContent(DetailView):
    # course_detail.html dosyasinda {{ icerik }} olarak goruntulenecek
    context_object_name = "icerik"
    template_name = "courses/course_detail.html"

    # kullanicinin kursa kayitli olup olmadidigini donduren metod
    def is_enrolled(self,pk):
        ogrenci = OUser.objects.get(username__iexact=self.request.user.username)  #ogrenciyi getir
        flag = False
        for crs in ogrenci.courses.all():  #ogrencinin aldigi tum dersleri incele
            if int(crs.courseID) == int(pk):    # id ler esit ise bayragi true yap dondur
                flag = True
        return flag

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated():
            if self.is_enrolled(self.kwargs['course_ID']):  #kullanici o derse kayitli ise o dersin icerik sayfasini
                return redirect('/kurs/'+self.kwargs['course_ID'] +'/icerik')               #goruntulesin
            else:
                self.object = self.get_object()
                return super(CourseContent, self).get(request, *args, **kwargs)
        else:
           self.object = self.get_object()
           return super(CourseContent, self).get(request, *args, **kwargs)

    def get_object(self):
        return Course.objects.filter(courseID__iexact=self.kwargs['course_ID'])[0]

    def get_context_data(self, **kwargs):
        context = super(CourseContent,self).get_context_data(**kwargs)
        return context


#http://127.0.0.1:8000/kurs/1/icerik/
class IcerikleriGoruntule(DetailView):
    context_object_name = "icerik"
    template_name = "courses/course_detail_.html"

    def get_object(self):
        ogrenci = OUser.objects.get(username__iexact=self.request.user.username)
        bayrak = False
        for crs in ogrenci.courses.all():
            if int(crs.courseID) == int(self.kwargs['course_ID']):
                bayrak = True
        if bayrak is True:
            return Lecture.objects.filter(course=self.kwargs['course_ID'])

    def get_context_data(self, **kwargs):
        context = super(IcerikleriGoruntule,self).get_context_data(**kwargs)
        context['bolumler'] = Section.objects.filter(course=self.kwargs['course_ID'])
        context['course_informations'] = Course.objects.filter(courseID=self.kwargs['course_ID'])[0]
        #context['lecture'] = Lecture.objects.filter(course=self.kwargs['course_ID'])[0]
        return context



#http://127.0.0.1:8000/kurs/1/icerik/ders
class IcerikGoruntule(DetailView):
    context_object_name = "icerik"
    template_name = "courses/content_detail.html"

    def get_object(self):
        ogrenci = OUser.objects.get(username__iexact=self.request.user.username)
        bayrak = False
        for crs in ogrenci.courses.all():
            if int(crs.courseID) == int(self.kwargs['course_ID']):
                bayrak = True
        if bayrak is True:
            return Lecture.objects.filter(slug=self.kwargs['slug'])



#http://127.0.0.1:8000/kurslar/
class CourseListView(ListView):
    model = Course
    template_name = "courses/course_list.html"

    def get_context_data(self, **kwargs):
        context = super(CourseListView,self).get_context_data(**kwargs)
        context['kategoriler'] = Category.objects.all()
        context['seviyeler'] = CourseLevels.objects.all()
        context['kurslar'] =  Course.objects.all().filter(course_isActive=True).order_by('courseStartDate')
        context['diller'] = CourseLanguage.objects.all()
        context['filter'] = CourseFilter(self.request.GET,queryset=Course.objects.all())

        return context


#ornek http://127.0.0.1:8000/kurslar/web
class CategoryListView(ListView):
    '''
        Belirli kategoriye ait kurslari listeler
        Ornek ofcourse.com/kurslar/web
        web kategorisindeki kurslari listeler.
    '''
    model = Course
    template_name = "courses/course_list.html"
    context_object_name = "icerik"

    def get_context_data(self, **kwargs):
        context = super(CategoryListView,self).get_context_data(**kwargs)
        context['kategoriler'] = Category.objects.all()
        context['seviyeler'] = CourseLevels.objects.all()
        context['kurslar'] =  Course.objects.all().filter(course_isActive=True,courseCategory=context['kategoriler']).order_by()
        context['diller'] = CourseLanguage.objects.all()
        return context



def enrollCourse(request,*args, **kwargs):
    ''' kursa katilmasini saglar'''
    if request.user.is_authenticated():
        n_kurs = Course.objects.get(courseID__iexact=kwargs['course_ID'])
        n_kurs = n_kurs.courseID
        ogrenci = get_object_or_404(OUser.objects.filter(username=request.user.username,is_student=True))
        print (n_kurs)
        ogrenci.courses.add(n_kurs)
        ogrenci.save()
        return HttpResponse('Kursa Katildin ..')       # duzenlenecek
    else:
        return redirect("/register")


def kurstanayril(request,*args, **kwargs):
    if request.user.is_authenticated():
        c = Course.objects.get(courseID=kwargs['course_ID'])
        o = OUser.objects.get(username=request.user.username).courses.remove(c)
        return HttpResponse("Kurstan Ayrildiniz...")
    else:
        return redirect("/")

templates/courses/content_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ icerik.name }} </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <link href="/site_media/css/bootstrap.min.css" rel="stylesheet" />
    <script src="/site_media/js/jquery.min.js"></script>
    <link href="/site_media/css/style.css" rel="stylesheet"/>
    <link href="/site_media/skins/default.css" rel="stylesheet" />

    <script>
    $(function(){
        $('#video').css({ width: $(window).innerWidth() + 'px', height: $(window).innerHeight() + 'px' });
        $(window).resize(function(){
            $('#video').css({ width: $(window).innerWidth() + 'px', height: $(window).innerHeight() + 'px' });
        });});
    </script>
    <style>body {overflow: hidden;}</style>
</head>
<body>
<iframe id="video" src="//www.youtube.com/embed/{{ icerik.video }}" frameborder="0" allowfullscreen></iframe>
</body>
</html>

templates/courses/course_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Kurs Detay</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <link href="/site_media/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/site_media/css/style.css" rel="stylesheet" />
    <link href="/site_media/skins/default.css" rel="stylesheet" />
    <script src="/site_media/js/jquery.min.js"></script>
</head>
<body>
{% include "base/nav.html" %}

<div class="main-top">
    <div class="container">
        <div class="row course-desc">
            <div class="col-md-12">
                <h1 class="course-title" data-purpose="course-title">{{ icerik.courseName }}</h1>
                <div class="by mb10 flex-col-xs">
                    <span class="mr30">
                        {% if icerik.courseInstructor %}
                            Eğitmen : <a href="">{{ icerik.courseInstructor }}</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="main-details mt10">
    <div class="container">
        <div class="row">

            <div class="col-lg-8 col-md-7" data-purpose="introduction-video">
                <div class="slp-promo-asset">
                    <div>
                        <iframe width="750" height="370" src="https://www.youtube.com/embed/{{ icerik.coursePreVideo }}" frameborder="0" allowfullscreen></iframe>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-5">
                <div class="row fxdc right-wrap mh0-force-md">
                    <div>

                        <div class="col-md-12 col-sm-6">
                            <div>
                                <a href="enroll" class="btn btn-lg btn-success ">Bu Kursa Devam Edin</a>
                            </div>

                        </div>
                        <div class="col-md-11 col-sm-6" >

                            <table class="table">
                            <tbody>
                        <tr>
                            {% if icerik.courseLevel  %}
                            <td><span class="list-left"></span><strong style="padding-right:2em;"> Seviye  </strong>:</td>
                                                        <td>{{ icerik.courseLevel }}</td>
                            {% endif %}<br>
                        </tr>
                        <tr>
                            {% if icerik.courseLanguage %}
                             <td>   <span class="list-left"></span><strong style="padding-right:2em;"> Dil : </strong> </td>
                                <td> {{ icerik.courseLanguage }} </td>
                            {% endif %}<br>
                        </tr>
                        <tr>
                            {% if icerik.courseCategory %}
                           <td><strong style="padding-right:2em;"> Kategori :</strong></td>
                                <td> {{ icerik.courseCategory }} </td>

                            {% endif %}<br>

                        </tr>
                        </div>
                        </tbody>
  </table>
                        <div class="clearfix visible-xs-block"></div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% if icerik.courseDesc %}
    <div class="container" >
        <div class="row">
            <div class="widget">
                <h5 class="widgetheading">
                    <strong>Kurs Açıklaması</strong><hr>
                    {{ icerik.courseDesc}}
                </h5>
            </div>
        </div>
    </div>
{% endif %}


<div class="container" >
    <div class="row">
        <div class="widget">
            <strong>Eğitmen Hakkında</strong><hr>
            <div class="col-lg-2 col-md-2">
                <img width="150" height="150"src="http://127.0.0.1:8000/media/{{ icerik.courseInstructor.profile_pic }}" />
            </div>
            <strong> Adı: </strong>  {{ icerik.courseInstructor.user.first_name }} {{ icerik.courseInstructor.user.last_name }}  <br>
            <strong> Biyografi: </strong> {{ icerik.courseInstructor.biography }}
        </div>
    </div>
</div>

{% include "base/footer.html" %}

</body>
</html>

templates/courses/course_detail_.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Kurs Detay</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <link href="/site_media/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/site_media/css/style.css" rel="stylesheet" />
    <link href="/site_media/js/style.css" rel="stylesheet" />
    <script src="/site_media/js/jquery.min.js"></script>
    <link href="/site_media/skins/default.css" rel="stylesheet" />
    <link href="/site_media/skins/main.css" rel="stylesheet" />
    <script>
     $(document).ready(function() {
       function close_accordion_section() {
          $('.accordion .accordion-section-title').removeClass('active');
          $('.accordion .accordion-section-content').slideUp(300).removeClass('open');
       }

      $('.accordion-section-title').click(function(e) {
           // Grab current anchor value
          var currentAttrValue = $(this).attr('href');

         if($(e.target).is('.active')) {
              close_accordion_section();
         }else {
                close_accordion_section();

                // Add active class to section title
                $(this).addClass('active');
                // Open up the hidden content panel
              $('.accordion ' + currentAttrValue).slideDown(300).addClass('open');
            }

           e.preventDefault();
     });
    });
    </script>

 </head>
<body>

{% include "base/nav.html" %}

<!-- kurs bilgileri -->
<div class="container-fluid" style="background-color:lightgray;" >
    <div>
        <div class="media">
            <a class="pull-left" href="#">
                <img class="media-object" style="padding:20px;" height="250" width="350" src="http://127.0.0.1:8000/media/{{ course_informations.courseCoverPhoto }}">
            </a>
            <div class="media-body">
                <h4 class="media-heading" style="padding-top: 20px;padding-bottom:20px;">
                    <b>{{ course_informations.courseName }}</b>
                </h4>
                <p>{{ course_informations.courseDesc }}.</p>
            </div>
        </div>
    </div>
</div>

<!--nav-->
<div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li class="active" style="padding-left:60px;padding-right: 40px;"><a href="#">Genel Bakış</a></li>
            <li style="padding-left:60px;padding-right: 30px;"><a href="#content">İçerik</a></li>
            <li style="padding-left:60px;padding-right: 30px;"><a href="http://127.0.0.1:8000/kurs/{{ course_informations.courseID }}/forum">Soru&Cevap</a></li>
            <li style="padding-left:60px;padding-right: 40px;"><a href="sil">Kurstan Ayrıl</a></li>
        </ul>
    </div>
</div>

<!--kurslar-->
<div class="container">
    <div class="row">
        <div id="content">
        {% for x in icerik %}
		<div class="widget widget-gray">
				<div class="widget-head" >
					<a href="{{ x.slug }}" target="_blank">
                        <h4 class="heading" >
                        <i class="fa fa-briefcase"></i>
                        {{ x.name }}</h4>
                    </a>
                </div>
        </div>
        {% endfor %}
        </div>
	</div>
</div>


</body>
</html>

templates/courses/course_list.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Kurs Detay </title>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="description" content="" />

<link href="/site_media/css/bootstrap.min.css" rel="stylesheet" />

<link href="/site_media/css/style.css" rel="stylesheet" />
<link href="/site_media/skins/default.css" rel="stylesheet" />

</head>

<body>
  <div id="wrapper">

    {% include "base/nav.html" %}
<hr>
    <div class="container">
        <div class="row row-offcanvas row-offcanvas-right">
            <div class="col-md-2 sidebar">
                {% block content %}
                    <form action="" method="get">
                        {% for filters in filter.form %}
                            {{ filters.label }} {{ filters }} <hr>
                        {% endfor %}
                        <input type="submit" value="Filtrele" />
                    </form>
                {% endblock %}
             </div>
            <div class="col-md-10 ">
              {%  if kurslar %}
                Toplam {{ kurslar|length }} kurs bulunmaktadir.
                  <hr>
                {% for kat in filter %}

                    {% ifequal kat.course_isActive True %}
                    <div class="col-lg-12">
                        <div class="col-sm-3">
                              <div class="row" >
                                    <div class="col-xs-8 col-xs-offset-2 col-sm-12 col-sm-offset-0">
                                        <a href="/kurs/{{ kat.courseID }}"> <img src="http://127.0.0.1:8000/media/{{ kat.courseCoverPhoto }}" height="170" width="290" class="img-responsive img-bordered center-block"></a>
                                    </div>
                              </div>
                        </div>

                        <div class="col-sm-9" >
                            <div class="row">
                                <div class="col-sm-8">
                                    <h3 class="">
                                        <a href="/kurs/{{ kat.courseID }}"> {{ kat.courseName }} </a>
                                          <span class="badges">
                                              {% if kat.courseLevel %}
                                            <span class="badge badge-squared badge-new text-uppercase">{{ kat.courseLevel }}</span>
                                            {% endif %}
                                            {% if kat.courseLanguage %}
                                            <span class="badge badge-squared badge-new text-uppercase">{{ kat.courseLanguage }}</span>
                                            {% endif %}
                                          </span>
                                    </h3>
                                  <span class="h6">Eğitmen: {{ kat.courseInstructor }} | Başlangıç: {{ kat.courseStartDate }}</span>
                              </div>
                            </div>

                            <div style="margin-top:3px;margin-bottom:50px;" >{{ kat.courseDesc }} </div>
                      </div>
                      </div>
                    {% endifequal %}

          {% endfor %}
          {% else %}
            Görüntülenecek Kurs bulunmamaktadir.
              {% endif %}

            </div>

                    </div>

          </div>

        </div>


     {% include "base/footer.html" %}
</div>
<script src="js/bootstrap.min.js"></script>
</body>
</html>

templates/courses/createcourse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Kurs Oluştur</title>
    <link href="/site_media/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/site_media/css/style.css" rel="stylesheet" />
    <link href="/site_media/skins/default.css" rel="stylesheet" />
<!-- <iframe width="560" height="315" src="https://www.youtube.com/embed/{{ icerik.coursePreVideo }}" frameborder="0" allowfullscreen></iframe> -->

</head>
<body>
  <div id="wrapper">
    {% include "base/nav.html" %}

    <div class="container">
      <div class="row">
      <div class="col-md-12 text-center">
          <form class="form-horizontal" action="{% url 'kursolustur' %}"  method="POST" >
                     {% csrf_token %}
                    <p>
                        <label for="id_courseName">Kurs Oluştur: </label>
                        <input id="id_courseName" name="courseName" type="text" />
                    </p>
                    <hr>
              <button id="signup" name="signup" class="btn btn-success">Oluştur</button>
          </form>

      </div>
</div>
</div>
  </div>

</body>
</html>

templates/courses/icerikekle.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

<link href="/site_media/css/bootstrap.min.css" rel="stylesheet" />
<link href="/site_media/css/style.css" rel="stylesheet" />
<link href="/site_media/css/panel.css" rel="stylesheet" />
<link href="/site_media/skins/default.css" rel="stylesheet" />
  <title>İçerik Ekle</title>
</head>


<body class="nav-md">
<div class="container body">
    {% include "base/nav.html" %}
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
        <div class="menu_section col-lg-2">
            <h3>Genel</h3>
            <ul class="nav side-menu">
                <li><a><i class="fa fa-home"></i> İçerik Ekle <span class="fa fa-chevron-down"></span></a></li>
            </ul>
            <hr>
            <h4> {{ icerik.courseName }} </h4>
            <ul class="nav side-menu">
                <li><a href="http://127.0.0.1:8000/kursduzenle/{{ icerik.courseID }}"><i class="fa fa-bug"></i> Kurs Bilgilerini Güncelle </a></li>
                <li><a href="http://127.0.0.1:8000/kursduzenle/{{ icerik.courseID }}/icerikekle"><i class="fa fa-bug"></i> İçerikleri Düzenle </a></li>
            </ul>
        </div>
    </div>

    <div class="col-lg-8">
        <form class="form-horizontal"   method="POST" >
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }} {{ field }}
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
            {% endfor %}
            <button id="update" name="update" class="btn btn-success">Ekle</button>
        </form>
    </div>
</div>
</div>
</div>
</body>
</html>

templates/courses/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Moderna - Bootstrap 3 flat corporate template</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="description" content="" />
<link href="/site_media/css/bootstrap.min.css" rel="stylesheet" />
</head>

<body>
{{ icerik.courseSlug }}
</body>
</html>

templates/courses/updatecourse.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/site_media/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/site_media/css/style.css" rel="stylesheet" />
    <link href="/site_media/css/panel.css" rel="stylesheet" />
    <link href="/site_media/skins/default.css" rel="stylesheet" />
    <title>Kurs Güncelle</title>
</head>


<body class="nav-md">
<div class="container body">
    {% include "base/nav.html" %}
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
        <div class="menu_section col-lg-2">
            <h3>Genel</h3>
            <ul class="nav side-menu">
                <li><a><i class="fa fa-home"></i> Kurs Ekle <span class="fa fa-chevron-down"></span></a></li>
            </ul>
            <hr>
            <h4> {{ icerik.courseName }} </h4>
            <ul class="nav side-menu">
                <li><a href="http://127.0.0.1:8000/kursduzenle/{{ icerik.courseID }}"><i class="fa fa-bug"></i> Kurs Bilgilerini Güncelle </a></li>
                <li><a href="http://127.0.0.1:8000/kursduzenle/{{ icerik.courseID }}/icerikekle"><i class="fa fa-bug"></i> İçerikleri Düzenle </a></li>
            </ul>
        </div>
    </div>

    <div class="col-lg-8">
        <form class="form-horizontal" method="POST" >
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <label class="col-md-4 control-label" for="nome">{{ field.label_tag }}</label>
                    {{ field.errors }}
                            <div class="col-md-5">
                                {{ field }}
                                <span class="help-block"></span>
                            </div>
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
            {% endfor %}
                 <div  class="text-center">
                    <button id="update" name="update" class="btn btn-success ">Güncelle</button>
                </div>
    </form>
    </div>
</div>
</div>
</div>
</body>
</html>